name: CI for Meal Search Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Замените на версию Node.js, которую вы используете

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: |
          mkdir -p build  # Создаем папку build
          cp -r ./public ./build  # Предположим, что ваши статические файлы находятся в папке public

      - name: Create test directory
        run: mkdir -p test  # Создаем директорию test, если она не существует

      - name: Run tests
        run: npm test  # Запускаем тесты с использованием Jest

      - name: Move test results
        run: |
          # Если ваши тесты генерируют какие-то результаты, переместите их в тестовую папку
          # Примерный перенос файла, если у вас есть результат в тестах
          # mv path/to/test-results/* test/

      # При необходимости, добавьте дополнительные шаги для деплоя или уведомлений
