name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка кода
      uses: actions/checkout@v2

    - name: Установка Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Укажите вашу версию Node.js

    - name: Установка зависимостей
      run: npm install

    - name: Запуск тестов
      run: npm test
